spring:
  application:
    name: hotkey-worker

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  data:
    redis:
      host: localhost
      port: 6379

zeta:
  worker:
    enabled: true

    threshold:
      hot-threshold: -1
      hot-threshold-ratio: 0.01

logging:
  level:
    io.github.hyshmily: INFO
