/*
 * Copyright 2026 Hyshmily. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hyshmily.zeta.worker.detection;

import io.github.hyshmily.zeta.worker.config.WorkerAutoConfiguration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLongArray;
import lombok.Getter;
import lombok.Setter;

/**
 * A high‑performance, lock‑free sliding‑window detector for real‑time hot‑key
 * identification.
 *
 * <h2>Why a sliding window?</h2>
 * A fixed‑window counter (e.g. reset every second) suffers from boundary
 * problems: a burst that straddles two windows can be split and go undetected.
 * The sliding window continuously aggregates the last {@code windowSize} time
 * slices, giving a smooth, instantaneous view of traffic for every key.
 *
 * <h2>Data structure</h2>
 * Each key owns an {@link AtomicLongArray} of length {@code 2 * windowSize},
 * used as a <b>circular buffer</b>.  The doubling avoids expensive array copies
 * when the window slides: old slices are lazily overwritten after a full
 * rotation, and a dedicated cleaning step zeros
 * them out before reuse.
 *
 * <h2>Concurrency</h2>
 * <ul>
 *   <li>Per‑key arrays are accessed only by the worker that owns the shard
 *       (thanks to consistent‑hash routing on the client side), so there is
 *       <b>no cross‑thread contention</b> on the same array.</li>
 *   <li>{@link AtomicLongArray} provides built-in atomic get/set/addAndGet on
 *       each element, guaranteeing visibility and atomicity of updates even
 *       though writes are single‑threaded — this protects against JVM
 *       reordering and ensures correct reads from the eviction thread.</li>
 *   <li>Unlike {@code AtomicLong[]}, every key owns exactly <b>one</b> object
 *       instead of {@code 2 × windowSize} objects, reducing memory overhead
 *       by ~94 % at scale.</li>
 *   <li>The {@code windows} and {@code lastAccessTime} maps use
 *       {@link ConcurrentHashMap} for safe concurrent access across keys and
 *       for the periodic eviction thread.</li>
 * </ul>
 *
 * <h2>Memory management</h2>
 * The {@link #evictStale(long)} method must be called periodically (e.g. every
 * few seconds) by a scheduler.  It removes any key that has not been accessed
 * within the given timeout, freeing the associated array and map entries.
 *
 * <h2>Dynamic threshold</h2>
 * The hot threshold is declared {@code volatile} and can be changed at runtime
 * via {@code setThreshold(long)} (generated by Lombok {@code @Setter}).  The {@link ThresholdLearner} periodically
 * updates this value based on estimated global qps.
 *
 * @see GlobalQpsEstimator
 * @see ThresholdLearner
 * @see WorkerAutoConfiguration.EvictStaleTask
 */
@Getter
@Setter
public class SlidingWindowDetector {

  /** Number of time slices that form one complete window. */
  private final int windowSize;

  /** Duration of a single time slice, in milliseconds. */
  private final long timeMillisPerSlice;

  /**
   * The access count a key must reach within the sliding window to be
   * considered "hot" for the current evaluation cycle.  Can be changed at
   * runtime (e.g. through JMX, a configuration refresh, or the
   * {@link ThresholdLearner}) because it is declared {@code volatile}.
   */
  private volatile long threshold;

  /**
   * Per‑key circular buffers using {@link AtomicLongArray} — a single flat
   * array per key instead of {@code AtomicLong[]} + 2*windowSize individual
   * objects.  This reduces memory from ~80 MB to ~5 MB for 100 k keys
   * (94 % reduction) with identical atomic-visibility guarantees.
   *
   * <p>Length is {@code 2 * windowSize} (doubled circular buffer).  The
   * current slice index is derived from
   * {@code System.currentTimeMillis() / timeMillisPerSlice % length}.
   */
  private final ConcurrentHashMap<String, AtomicLongArray> windows = new ConcurrentHashMap<>();

  /**
   * Last access timestamp (epoch millis) for each key.  Used solely by
   * {@link #evictStale(long)} to identify and remove idle keys.
   */
  private final ConcurrentHashMap<String, Long> lastAccessTime = new ConcurrentHashMap<>();

  /**
   * Constructs a detector.
   *
   * @param windowDurationMs total duration of the sliding window in milliseconds
   * @param slices           number of time slices within the window (determines
   *                         the granularity of the sliding)
   * @param threshold        initial hot‑key threshold
   */
  public SlidingWindowDetector(long windowDurationMs, int slices, long threshold) {
    if (slices <= 0) throw new IllegalArgumentException("slices must be positive, got " + slices);
    if (windowDurationMs < slices) throw new IllegalArgumentException("windowDurationMs (" + windowDurationMs + ") must be >= slices (" + slices + ") to avoid division by zero");
    this.windowSize = slices;
    this.timeMillisPerSlice = windowDurationMs / slices;
    this.threshold = threshold;
  }

  /**
   * Records an access count for the given key and immediately evaluates
   * whether the key is "hot" in the current window.
   *
   * <p>If this is the first access for the key, a new circular buffer is
   * created atomically.  The current time slice is updated with the given
   * count, stale slices (older than one full window) are zeroed, and the
   * window sum is compared against the current threshold.
   *
   * @param key   the cache key; must not be {@code null}
   * @param count the number of accesses to reportToWorker (typically the batched
   *              count reported by an application instance)
   * @return {@code true} if the sum of the last {@link #windowSize} slices
   *         meets or exceeds {@link #threshold}; {@code false} otherwise
   * @throws NullPointerException if {@code key} is {@code null}
   */
  public boolean addCount(String key, long count) {
    long now = System.currentTimeMillis();

    AtomicLongArray slices = windows.get(key);
    if (slices == null) {
      slices = windows.computeIfAbsent(key, k -> new AtomicLongArray(windowSize * 2));
    }

    int currentIndex = (int) ((now / timeMillisPerSlice) % slices.length());

    lastAccessTime.put(key, now);

    // Single pass: clear stale slices then sum window
    int length = slices.length();
    int clearStart = (currentIndex + windowSize) % length;
    long sum = 0;
    for (int i = 0; i < windowSize; i++) {
      int idx = (clearStart - i + length) % length;
      slices.set(idx, 0);
    }
    slices.addAndGet(currentIndex, count);
    for (int i = 0; i < windowSize; i++) {
      int idx = (currentIndex - i + length) % length;
      sum += slices.get(idx);
    }

    return sum >= threshold;
  }

  /**
   * Evicts stale tracking data for keys that have not been accessed within the
   * given timeout.  Unlike a simple two‑step {@code removeIf}, this implementation
   * uses atomic re‑verification to eliminate a race window between the two maps:
   * an {@code addCount} that updates the timestamp after the first pass will be
   * correctly detected and the key will be kept.
   *
   * <p>Must be called periodically (e.g. via
   * {@link WorkerAutoConfiguration.EvictStaleTask}) to prevent unbounded memory
   * growth from keys that are no longer accessed.
   *
   * @param staleAfterMs maximum idle time in milliseconds before a key is
   *                     considered stale and evicted; must be non-negative
   */
  public void evictStale(long staleAfterMs) {
    long now = System.currentTimeMillis();

    // This is a best‑effort snapshot; concurrent addCount calls may update
    // lastAccessTime after this collection, so we must re‑check later.
    List<String> candidates = new ArrayList<>();
    lastAccessTime.forEach((key, ts) -> {
      if (now - ts > staleAfterMs) {
        candidates.add(key);
      }
    });

    for (String key : candidates) {
      windows.compute(key, (k, arr) -> {
        // Re‑read the latest access time – this guards against the race
        // where addCount() updated the timestamp after we collected the key.
        Long currentTs = lastAccessTime.get(k);

        // If the timestamp has been refreshed (or the key already gone),
        // the entry is still active – keep the window array.
        if (currentTs == null || now - currentTs <= staleAfterMs) {
          return arr;
        }

        // The key is genuinely stale.  Conditionally remove the timestamp
        // entry ONLY if it still holds the same old value.  If addCount()
        // concurrently updated the timestamp, remove() will fail, and we
        // must retain the window array.  The conditional remove is atomic
        // and avoids introducing a lock or synchronized block.
        lastAccessTime.remove(k, currentTs);

        // Returning null deletes the window array from the windows map.
        return null;
      });
    }

    // This handles corner cases where a window array was removed but the
    // corresponding timestamp entry survived (e.g. due to a prior race that
    // has now been fixed).
    lastAccessTime.keySet().removeIf(k -> !windows.containsKey(k));
  }

  /**
   * Returns the total access count within the current sliding window for the
   * given key, or {@code 0} if the key is unknown.
   *
   * @param key the cache key to query
   * @return the sum of access counts in the current window, or {@code 0} if
   *         the key is not being tracked
   */
  public long getWindowSum(String key) {
    AtomicLongArray slices = windows.get(key);
    if (slices == null) {
      return 0;
    }
    int currentIndex = (int) ((System.currentTimeMillis() / timeMillisPerSlice) % slices.length());
    long sum = 0;
    int length = slices.length();
    for (int i = 0; i < windowSize; i++) {
      int idx = (currentIndex - i + length) % length;
      sum += slices.get(idx);
    }
    return sum;
  }

  /**
   * Returns the number of keys currently being tracked by this detector.
   *
   * <p>This includes all keys with allocated circular buffers, regardless
   * of whether they have expired but have not yet been evicted.
   *
   * @return the count of active keys in the windows map
   */
  public int getActiveKeyCount() {
    return windows.size();
  }
}
