/*
 * Copyright 2026 Hyshmily. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hyshmily.zeta.util;

import io.github.hyshmily.zeta.Internal;

/**
 * Fixed-point and bit-manipulation math primitives shared across the
 * detection and cache paths. One home for the three pure-function math
 * families the codebase ports from systems sources:
 *
 * <ul>
 * <li><b>Kernel decay math</b> — the PELT half-life table
 * ({@code kernel/sched/pelt.c}, {@code y^32 = 1/2}) read as an O(1) decay
 * factor for any elapsed time: the shape behind every "lazy decay" signal
 * (decay on read by an arbitrary elapsed time, no background sweeper, O(1)
 * regardless of the gap).</li>
 * <li><b>FastRange bucket mapping</b> — RocksDB {@code util/fastrange.h}:
 * map a hash into {@code [0, range)} via the high half of the
 * {@code range × hash} product instead of a modulo.</li>
 * <li><b>Power-of-two alignment</b> — the JDK {@code highestOneBit} idiom
 * shared by the bit-masked structures (HeavyKeeper sketch/table/stripes,
 * RollingWindow buckets).</li>
 * </ul>
 *
 * <p>All methods are pure functions and stateless; the class is
 * non-instantiable. Cross-validations live in {@code FastMathTest}.
 */
@Internal
public final class FastMath {

  /** One halving every this many periods: {@code y^32 = 1/2} ({@code pelt.c} {@code LOAD_AVG_PERIOD}). */
  private static final int PERIOD_SHIFT = 5;
  private static final int PERIOD_MASK = (1 << PERIOD_SHIFT) - 1;

  /**
   * Kernel cap: periods beyond this return an exact zero ({@code pelt.c:36-37},
   * {@code n > LOAD_AVG_PERIOD * 63}). {@code y^2016 = 2^-63} — below 64-bit resolution, and
   * far below any signal resolution for the double APIs too.
   */
  public static final long MAX_PERIODS = 32L * 63;

  /** ln 2 as fixed point 693147/10^6 (relative error 1.5e-7, absorbed by the period rounding). */
  private static final long LN2_NUM = 693_147L;
  private static final long LN2_DEN = 1_000_000L;

  /**
   * Supported time-constant ceiling, ~11.6 days in ms. Only exists to keep
   * {@code tc * LN2_NUM} and the rounding addition inside 64 bits; real Zeta time constants
   * (window spans, EMA half-lives) are orders of magnitude below it. Larger values are clamped.
   */
  private static final long MAX_TIME_CONSTANT_MS = 1_000_000_000L;

  /**
   * Elapsed-ms ceiling for {@link #expDecayFactor}. Chosen as the largest value whose product
   * with 32·10^6 stays inside {@code Long.MAX_VALUE} (so the period computation below cannot
   * wrap); at this gap the exact factor is {@code e^-280 ≈ 1e-122} for the largest supported
   * time constant — zero for every signal purpose.
   */
  private static final long MAX_ELAPSED_MS = 280_000_000_000L;

  /**
   * {@code runnable_avg_yN_inv} verbatim from the generated kernel header
   * ({@code kernel/sched/sched-pelt.h}, "Generated by Documentation/scheduler/sched-pelt;
   * do not modify"): {@code T[i] = round(2^32 · y^i)} with {@code y^32 = 1/2}, stored as u32 —
   * hence {@code T[0] = 0xffffffff}, one ulp under {@code 2^32}. {@code FastMathTest}
   * cross-checks every entry against the closed form, so a transcription typo cannot ship.
   */
  static final long[] Y_N_INV = {
    0xffffffffL,
    0xfa83b2daL,
    0xf5257d14L,
    0xefe4b99aL,
    0xeac0c6e6L,
    0xe5b906e6L,
    0xe0ccdeebL,
    0xdbfbb796L,
    0xd744fcc9L,
    0xd2a81d91L,
    0xce248c14L,
    0xc9b9bd85L,
    0xc5672a10L,
    0xc12c4cc9L,
    0xbd08a39eL,
    0xb8fbaf46L,
    0xb504f333L,
    0xb123f581L,
    0xad583ee9L,
    0xa9a15ab4L,
    0xa5fed6a9L,
    0xa2704302L,
    0x9ef5325fL,
    0x9b8d39b9L,
    0x9837f050L,
    0x94f4efa8L,
    0x91c3d373L,
    0x8ea4398aL,
    0x8b95c1e3L,
    0x88980e80L,
    0x85aac367L,
    0x82cd8698L,
  };

  /**
   * The same 32 factors as doubles, {@code Y_N_INV[i] / 2^32}, precomputed at class init.
   * Dividing an integer-valued double by {@code 2^32} is exact (a pure exponent
   * decrement), so the precomputed entry is bit-identical to computing
   * {@code Y_N_INV[i] / 4294967296.0} per call — this just replaces that per-call
   * long→double conversion plus division with one array load on the decay path.
   */
  private static final double[] Y_N_INV_D = new double[Y_N_INV.length];

  static {
    for (int i = 0; i < Y_N_INV.length; i++) {
      Y_N_INV_D[i] = Y_N_INV[i] / 4294967296.0;
    }
  }

  /**
   * {@code y^n} as a double factor for floating-point lazy-decay state — the PELT
   * {@code y^32 = 1/2} table, read side. {@code n = 0} yields exactly {@code 1.0};
   * {@code n >} {@link #MAX_PERIODS} yields exactly {@code 0.0} (the kernel's u64 cap — for
   * doubles {@code y^2017 ≈ 9e-20} would still be representable, but keeping one cap across
   * the factor APIs makes "decayed to nothing" mean the same thing everywhere).
   *
   * @param n elapsed periods, {@code >= 0}
   * @return the decay factor in {@code [0, 1]}
   */
  public static double decayFactor(long n) {
    if (n < 0) {
      throw new IllegalArgumentException("decayFactor period must be non-negative: " + n);
    }
    if (n == 0) {
      return 1.0;
    }
    if (n > MAX_PERIODS) {
      return 0.0;
    }
    // y^n = 2^-(n/32) · y^(n%32): one table load, one scalb — no exp, no pow, no division.
    return Math.scalb(Y_N_INV_D[(int) (n & PERIOD_MASK)], -(int) (n >> PERIOD_SHIFT));
  }

  /**
   * Decay factor for elapsed wall time against a time constant: ≈ {@code exp(-elapsedMs /
   * timeConstantMs)} — the shape {@code PerKeyEvalState}-style lazy decays need — computed
   * through the PELT table in O(1). The half-life is {@code timeConstantMs · ln 2}; the period
   * count is rounded to the nearest integer, which bounds the factor's quantization error at
   * {@code 1 − y^0.5 ≈ 1.07%} relative (pinned against {@code Math.exp} in
   * {@code FastMathTest}).
   *
   * <p>
   * Time-rollback convention built in: {@code elapsedMs <= 0} returns {@code 1.0} — the caller
   * re-anchors its timestamp and this update decays nothing (the kernel drops the update and
   * resets {@code last_update_time}, {@code pelt.c:186-194}). Huge deltas clamp internally:
   * gaps beyond ~8.9 years (or periods beyond {@link #MAX_PERIODS}) return {@code 0.0} instead
   * of shifting by a garbage count.
   *
   * @param elapsedMs      non-negative elapsed milliseconds; non-positive returns {@code 1.0}
   * @param timeConstantMs the e-folding time in ms, in {@code (0, ~11.6 days]} — larger values
   *                       are clamped to the supported ceiling
   * @return the decay factor in {@code [0, 1]}
   */
  public static double expDecayFactor(long elapsedMs, long timeConstantMs) {
    if (elapsedMs <= 0 || timeConstantMs <= 0) {
      // pelt.c:186-194 port: a non-positive delta is a protocol event, not data —
      // no-op decay, and the caller re-anchors.
      return 1.0;
    }
    long tc = Math.min(timeConstantMs, MAX_TIME_CONSTANT_MS);
    if (elapsedMs > MAX_ELAPSED_MS) {
      return 0.0;
    }
    // n = round(elapsed · 32 / (tc · ln2)), with ln2 as fixed point LN2_NUM/LN2_DEN:
    // n = round(elapsed·32·10^6 / (tc·693147)). Both products are pre-bounded
    // (elapsed ≤ 2.8e11 × 3.2e7 = 8.96e18; tc ≤ 1e9 × 693147 = 6.93e14) so the
    // rounding addition cannot wrap. (32·10^6 must stay a literal — the nearest
    // power of two, 2^25 = 33_554_432, would skew every time constant by ~4.9%.)
    long num = elapsedMs * 32_000_000L;
    long den = tc * LN2_NUM;
    long n = (num + (den >> 1)) / den;
    return decayFactor(n);
  }

  /**
   * Map a 32-bit hash into {@code [0, range)}:
   * {@code (range × uint32(hash)) >>> 32}.
   *
   * <p>Distribution is equivalent to unsigned modulo for a perfectly
   * distributed hash, but consumes all 32 bits of entropy and costs one
   * multiply instead of one division.
   *
   * <p><b>Precondition</b> (the {@code fastrange.h} L92-93 warning): the hash
   * must be the natural output width of a quality hash function — a 32-bit
   * value goes through this method; feeding a 32-bit hash to a 64-bit
   * variant "gives extremely bad results, mostly zero". The 64-bit variant
   * (128-bit product via {@code Math.multiplyHigh}) is deliberately not
   * provided until a 64-bit-hash caller exists.
   *
   * @param hash  the hash value (all 32 bits are consumed)
   * @param range the bucket count, must be positive
   * @return the bucket index in {@code [0, range)}
   */
  public static int fastRange32(int hash, int range) {
    return (int) (((hash & 0xFFFFFFFFL) * range) >>> 32);
  }


  /**
   * Round {@code v} up to the smallest power of two ≥ {@code v}; a value that
   * is already a power of two (including 1) is returned unchanged.
   *
   * @param v the value to align; must be ≥ 1
   * @return the aligned power of two
   */
  public static int pow2Ceil(int v) {
    return (v & (v - 1)) == 0 ? v : Integer.highestOneBit(v - 1) << 1;
  }

  /** Non-instantiable. */
  private FastMath() {}
}
